.\" Manpage for simple_shell
.TH man 1 "28 July 2024" "0.1" "simple_shell man page"
.SH NAME
simple_shell \- our simple shell program
.SH SYNOPSIS
.B Our simple_shell program
.TP
.B info to be added
more info...
.SH DESCRIPTION
.B simple_shell
a shell that takes input from a user and executes if the command is available
.SH OPTIONS
.TP
.B \- exit
exits program
.TP
.B \- ls
list
.TP
.B \- -l
list long
.SH EXAMPLE
.TP
.B \- $ ls
.TP
.B \- We are forking
.TP
.B \- /bin/ls
.TP
.B \- check_build.c   main.h          path_get.c      test_dir
.TP
.B \- get_tokens.c    mike_test.c     shell
.TP
.B \- $ 
.TP
.SH BUGS
.B known bugs....
.SH AUTHORS
.B Michael Ballou,
.B Tristian Davis
.SH COPYRIGHT
.B Cool Guys
